{
 "title": "demo",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "rp_hosts",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rp_hosts_enable{}" }
   ]
  },
  {
   "title": "rp_hosts_active",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rp_hosts_active{}" }
   ]
  },
  {
   "title": "rp_hosts_active",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    { "expr": "rp_hosts_enable{}", "legendFormat": "pid {{pid}}" }
   ]
  },
  {
   "title": "rp_hosts_running",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "rp_hosts_running{}", "legendFormat": "pid {{pid}}" }
   ]
  },
  {
   "title": "rp_hosts_memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "targets": [
    { "expr": "rp_hosts_memory{}", "legendFormat": "pid {{pid}} " }
   ]
  },
  {
   "title": "rp_hosts_connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 6 },
   "targets": [
    { "expr": "rp_hosts_connections{}", "legendFormat": "pid {{pid}} " }
   ]
  },
  {
   "title": "rp_hosts_avg_threads",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 6 },
   "targets": [
    { "expr": "rp_hosts_avg_threads{}", "legendFormat": "pid {{pid}} " }
   ]
  },
  {
   "title": "rp_hosts_available_perfomance",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "rp_hosts_available_perfomance{}",
     "legendFormat": "pid {{pid}} "
    }
   ]
  },
  {
   "title": "rp_hosts_avg_call_time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
   "targets": [
    { "expr": "rp_hosts_avg_call_time{}", "legendFormat": "pid {{pid}} " }
   ]
  },
  {
   "title": "rp_hosts_selection_size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 12 },
   "targets": [
    { "expr": "rp_hosts_selection_size{}", "legendFormat": "pid {{pid}} " }
   ]
  },
  {
   "title": "rp_hosts_memory_excess_time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "targets": [
    { "expr": "rp_hosts_memory_excess_time{}", "legendFormat": "pid {{pid}} " }
   ]
  },
  {
   "title": "rp_hosts_available_capacity",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "targets": [
    { "expr": "rp_hosts_capacity{}", "legendFormat": "pid {{pid}} " }
   ]
  },
  {
   "title": "rp_hosts_avg_db_call_time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "targets": [
    { "expr": "rp_hosts_avg_db_call_time{}", "legendFormat": "pid {{pid}} " }
   ]
  },
  {
   "title": "rp_hosts_avg_db_call_time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "targets": [
    { "expr": "rp_hosts_avg_db_call_time{}", "legendFormat": "pid {{pid}} " }
   ]
  },
  {
   "title": "rp_hosts_avg_server_call_time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rp_hosts_avg_server_call_time{}",
     "legendFormat": "pid {{pid}} "
    }
   ]
  },
  {
   "title": "rp_hosts_avg_back_call_time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "targets": [
    { "expr": "rp_hosts_avg_back_call_time{}", "legendFormat": "pid {{pid}} " }
   ]
  }
 ]
}