# .github/workflows/release.yaml

on:
  release:
    types:
      - created

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.RELEASE_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: ./cmd/app/
